# Params for Twitter-Agent

# Follow Back Followers
min_follower_count: 50
max_follower_count: 5000
follow_back_probability: 0.6

# Like Probability
relevant_like_probability: 0.35
irrelevant_like_probability: 0.15

# Retweet Probability
retweet_probability: 0.15
follower_factor: 2

# Response Probabilities:
reply_to_new_direct_messages: 0.05
quote_tweet: 0.3
post_tweet: 0.3
like_timeline_tweets: 0.15
respond_to_timeline_tweets: 0.2

# DM reply probability
should_respond_probability: 0.85

# GIF reply probability
gif_respond_probability: 0.25
text_respond_probability: 0.25
reply_probability: 0.25

response_probability: 0.1
like_probability: 0.3
retweet_probability: 0.1
action_threshold: 0.8
